-- 1.3.6.1.4.1
SNIFFLE-MIB DEFINITIONS ::= BEGIN

    IMPORTS
        experimental   FROM RFC1155-SMI
        RowStatus      FROM STANDARD-MIB
        DisplayString  FROM RFC1213-MIB
        OBJECT-TYPE    FROM RFC-1212
        enterprises    FROM SNMPv2-SMI
        ;

    fifo         OBJECT IDENTIFIER ::= { enterprises 41822 }
-- Group section
    sniffle      OBJECT IDENTIFIER ::= { fifo 2 }
    general      OBJECT IDENTIFIER ::= { sniffle 1 }

-- General section.
    name OBJECT-TYPE
        SYNTAX  DisplayString (SIZE (0..255))
        ACCESS  read-only
        STATUS  mandatory
        DESCRIPTION
            "My own name"
        ::= { general 1 }

    version OBJECT-TYPE
        SYNTAX  DisplayString (SIZE (0..255))
        ACCESS  read-only
        STATUS  mandatory
        DESCRIPTION
            "sniffle version"
        ::= { general 2 }

    ringStatus OBJECT-TYPE
        SYNTAX  INTEGER
        ACCESS  read-only
        STATUS  mandatory
        DESCRIPTION
            "ring status"
        ::= { general 3 }

END