#!/usr/bin/env bash

case $1 in
    diag)
        echo "Running diagnostics for installed services."
        [ -f /opt/local/fifo-snarl/share/snarl-diag ] && /opt/local/fifo-snarl/share/snarl-diag
        [ -f /opt/local/fifo-sniffle/share/sniffle-diag ] && /opt/local/fifo-sniffle/share/sniffle-diag
        [ -f /opt/local/fifo-howl/share/howl-diag ] && /opt/local/fifo-howl/share/howl-diag
        [ -f /opt/local/fifo-wiggle/share/wiggle-diag ] && /opt/local/fifo-wiggle/share/wiggle-diag
        ;;
    roles|users)
        if [ -f /opt/local/fifo-snarl/bin/snarl-admin ]
        then
            /opt/local/fifo-snarl/bin/snarl-admin $@
        else
            echo "Snarl is not installed. Sorry!"
            exit 1
        fi
        ;;
    vms|hypervisors|packages|datasets|ipranges|networks|dtrace)
        if [ -f /opt/local/fifo-sniffle/bin/sniffle-admin ]
        then
            if [ "$2" == "export" ]
            then
                /opt/local/fifo-sniffle/bin/sniffle-admin $1 $2 $3 "$( readlink -f "$( dirname "$4" )" )/$( basename "$4")"
            else
                if [ "$2" == "import" ]
                then
                    if [ "$4" == "" ]
                    then
                        /opt/local/fifo-sniffle/bin/sniffle-admin $1 $2 "$( readlink -f "$( dirname "$3" )" )/$( basename "$3")"
                    else
                        /opt/local/fifo-sniffle/bin/sniffle-admin $1 $2 "$( readlink -f "$( dirname "$3" )" )/$( basename "$3")" "$( readlink -f "$( dirname "$4" )" )/$( basename "$4")"
                    fi
                else
                    /opt/local/fifo-sniffle/bin/sniffle-admin $@
                fi
            fi
        else
            echo "Sniffle is not installed. Sorry!"
            exit 1
        fi
        ;;
    help|?)
        cat <<EOF
fifoadm administers snarl and sniffle.
EOF
        ;;
    *)
        echo "Unknown command $1, valid are: "
        echo "  snarl:   roles, users"
        echo "  sniffle: vms, hypervisors, packages, datasets, networks, dtrace"
        echo "  general: help, diag"
        exit 1
        ;;
esac
